import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import type { NextPage } from "next";

import Nav from "../components/Nav";
import CollegeRankItem from "../components/CollegeRankItem";
import { fetchWrapper } from "../helpers/fetch-wrapper";
import { createFuzzyMatcher } from "../lib/util";

interface collegeInfoType {
  college_name: string;
  number_of_students: number;
  college_id: number;
}
interface props {
  college: collegeInfoType[];
}

const Home: NextPage<props> = ({ college }) => {
  const cl = college;

  const [collegeList, setCollegeList] = useState<collegeInfoType[]>(cl);

  const onSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setCollegeList(
      cl.filter((college: collegeInfoType) =>
        createFuzzyMatcher(e.target.value).test(college["college_name"])
      )
    );
  };

  return (
    <div>
      <div className="img-background">
        <Image src="/background.png" layout="fill" objectFit="cover" />
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="cover">
        <div className="content">
          <span className="logo">맛집대학</span>
          <div className="input-box">
            <input
              type="text"
              placeholder="학교이름으로 검색해보세요"
              onChange={onSearchChange}
              autoComplete="off"
            />
            <div className="image-wrapper">
              <Image src="/search.png" width={30} height={30} alt="search" />
            </div>
          </div>
          <div className="school-rank">
            {collegeList.map(
              (info, i) =>
                i < 8 && (
                  <CollegeRankItem
                    collegeName={info["college_name"]}
                    studentNum={info["number_of_students"]}
                    collegeId={info["college_id"]}
                    key={i}
                  />
                )
            )}
          </div>
        </div>
        <Nav />
      </div>
      <style jsx>
        {`
          .img-background {
            z-index: 1;
            width: 100vw;
            height: 100vh;
          }
          .cover {
            position: absolute;
            top: 0;
            left: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100vw;
            height: 100vh;
            z-index: 2;
            background-color: rgba(255, 255, 255, 0.5);

            .content {
              display: flex;
              flex-direction: column;
              align-items: center;

              .logo {
                font-family: "Nanum Pen Script";
                font-size: 6rem;
                padding-left: 4rem;
                letter-spacing: 4rem;
              }

              .input-box {
                position: relative;
                margin: 70px 0;
                input {
                  width: 540px;
                  height: 50px;
                  border-radius: 10px;
                  border: none;
                  padding: 0 50px;
                  font-size: 20px;
                  box-shadow: 1px 2px 2px black;
                  outline: none;
                }
                input::placeholder {
                  font-size: 15px;
                  text-align: center;
                }
                .image-wrapper {
                  position: absolute;
                  top: 10px;
                  left: 8px;
                }
              }

              .school-rank {
                width: 400px;
                height: fit-content;
                min-height: 400px;
                max-height: 400px;
                overflow-y: hidden;
              }
            }
          }

          @media (max-width: 780px) {
            .cover {
              .content {
                .logo {
                  font-size: 4rem;
                  padding-left: 3rem;
                  letter-spacing: 3rem;
                }

                .input-box {
                  margin: 63px 0;
                  input {
                    width: 400px;
                    height: 45px;
                    padding: 0 45px;
                    font-size: 18px;
                  }
                  input::placeholder {
                    font-size: 15px;
                    text-align: center;
                  }
                  .image-wrapper {
                    position: absolute;
                    top: 9px;
                    left: 8px;
                  }
                }

                .school-rank {
                  width: 360px;
                  height: fit-content;
                  max-height: 360px;
                  overflow-y: hidden;
                }
              }
            }
          }

          @media (max-width: 545px) {
            .cover {
              .content {
                .input-box {
                  margin: 63px 0;
                  input {
                    width: 350px;
                    height: 45px;
                    padding: 0 45px;
                    font-size: 18px;
                  }
                }

                .school-rank {
                  width: 300px;
                  height: fit-content;
                  max-height: 360px;
                  overflow-y: hidden;
                }
              }
            }
          }

          @media (max-width: 480px) {
            .cover {
              .content {
                .logo {
                  font-size: 3rem;
                  padding-left: 2rem;
                  letter-spacing: 2rem;
                }

                .input-box {
                  input {
                    width: 200px;
                    height: 45px;
                    padding: 0 50px;
                    font-size: 15px;
                  }
                  input::placeholder {
                    font-size: 13px;
                    text-align: center;
                  }
                  .image-wrapper {
                    position: absolute;
                    top: 9px;
                    left: 10px;
                  }
                }

                .school-rank {
                  width: 240px;
                  height: fit-content;
                  max-height: 360px;
                  overflow-y: hidden;
                }
              }
            }
          }
        `}
      </style>
    </div>
  );
};

export async function getServerSideProps() {
  const url = `${process.env.NEXT_PUBLIC_SERVER_IP}/common/college-student-count`;
  let resp: any = await fetchWrapper.post(url, {});

  return { props: { college: resp } };
}
export default Home;
