import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import Map from "../components/Map";
import CollegeRankItem from "../components/CollegeRankItem";

const Home: NextPage = () => {
  let schoolInfo = [
    { collegeName: "서울시립대", studentNum: 563 },
    { collegeName: "경희대", studentNum: 321 },
    { collegeName: "중앙대", studentNum: 123 },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
      <div className="cover">
        <div className="content">
          <span className="logo">맛집대학</span>
          <div className="input-box">
            <input type="text" placeholder="학교이름으로 검색해보세요" />
            <div className="image-wrapper">
              <Image src="/search.png" width={30} height={30} alt="search" />
            </div>
          </div>
          <div className="school-rank">
            {schoolInfo.map((info, i) => (
              <CollegeRankItem
                collegeName={info.collegeName}
                studentNum={info.studentNum}
                key={i}
              />
            ))}
          </div>
        </div>
      </div>
      <style jsx>
        {`
          .cover {
            position: absolute;
            top: 0;
            left: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100vw;
            height: 100vh;
            z-index: 2;
            background-color: rgba(255, 255, 255, 0.5);

            .content {
              display: flex;
              flex-direction: column;
              align-items: center;
              .logo {
                font-family: "Nanum Pen Script";
                font-size: 4rem;
                padding-left: 4rem;
                letter-spacing: 4rem;
              }

              .input-box {
                position: relative;
                margin: 70px 0;
                input {
                  width: 540px;
                  height: 50px;
                  border-radius: 10px;
                  border: none;
                  padding: 0 50px;
                  font-size: 20px;
                  box-shadow: 1px 2px 2px black;
                  outline: none;
                }
                input::placeholder {
                  font-size: 15px;
                  text-align: center;
                }
                .image-wrapper {
                  position: absolute;
                  top: 10px;
                  left: 8px;
                }
              }

              .school-rank {
                width: 400px;
                height: fit-content;
                max-height: 400px;
                overflow-y: hidden;
              }
            }
          }
        `}
      </style>
    </div>
  );
};

export default Home;
